// app/api/admin/approve/route.ts
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";
import { Octokit } from "octokit";
import Papa from "papaparse";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const OWNER = process.env.GITHUB_OWNER!;
const REPO = process.env.GITHUB_REPO!;
const PATH = process.env.CSV_PATH!;
const BASE_BRANCH = process.env.GITHUB_BRANCH || 'main';

export async function POST(req: Request) {
    const session = await auth();
    // @ts-ignore
    if (!session || session.user?.role !== 'ADMIN') {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    try {
        const { requestId } = await req.json();
        
        const request = await prisma.request.findUnique({ 
            where: { id: requestId },
            include: { user: true }
        });
        if (!request) return NextResponse.json({ error: "Request not found" }, { status: 404 });
        if (request.status !== 'PENDING') return NextResponse.json({ error: "Request already processed" }, { status: 400 });

        // 1. Get current CSV from GitHub
        const { data: fileData } = await octokit.rest.repos.getContent({
            owner: OWNER,
            repo: REPO,
            path: PATH,
            ref: BASE_BRANCH,
        });

        if (!('content' in fileData)) throw new Error("No content found");
        const content = Buffer.from(fileData.content, 'base64').toString('utf-8');
        const parsed = Papa.parse(content, { header: true, skipEmptyLines: true });
        const rows = parsed.data as any[];
        
        const payload = JSON.parse(request.payload);
        const original = request.originalTerm ? JSON.parse(request.originalTerm) : null;

        // 2. Apply Changes
        if (request.type === 'ADD') {
            rows.push(payload);
        } else if (request.type === 'EDIT' && original) {
            // Fuzzy match logic or strict match? Let's strict match English and Category
            const index = rows.findIndex(row => 
                row['Full Form (English)'] === original['Full Form (English)']
            );
            
            if (index !== -1) {
                // Preserve original ordering of keys if possible, but Papa handles unparse ok.
                // We overwrite with new payload
                rows[index] = { ...rows[index], ...payload };
            } else {
                 return NextResponse.json({ error: "Original term not found in CSV" }, { status: 409 });
            }
        }

        const newCsv = Papa.unparse(rows);
        if (newCsv === content) {
             return NextResponse.json({ error: "No changes detected" }, { status: 400 });
        }
        
        const shortId = requestId.slice(-6);
        const newBranchName = `glossary-${shortId}`;

        // 3. Create Branch
        const { data: refData } = await octokit.rest.git.getRef({
            owner: OWNER,
            repo: REPO,
            ref: `heads/${BASE_BRANCH}`,
        });
        
        // Check if branch exists, if so delete? No, unique ID.
        await octokit.rest.git.createRef({
            owner: OWNER,
            repo: REPO,
            ref: `refs/heads/${newBranchName}`,
            sha: refData.object.sha,
        });

        // 4. Update File in new Branch
        await octokit.rest.repos.createOrUpdateFileContents({
            owner: OWNER,
            repo: REPO,
            path: PATH,
            message: `feat: glossary update ${shortId}`,
            content: Buffer.from(newCsv).toString('base64'),
            branch: newBranchName,
            sha: fileData.sha, 
        });

        // 5. Create PR
        const submitter = request.user?.name ? `${request.user.name} (${request.user.email})` : request.user?.email || 'Unknown User';
        const approver = session.user?.name ? `${session.user.name} (${session.user.email})` : session.user?.email;

        const { data: pr } = await octokit.rest.pulls.create({
            owner: OWNER,
            repo: REPO,
            title: `Glossary Update: ${request.type} Term (${shortId})`,
            body: `Requested by: **${submitter}**\n\nApproved by: ${approver}\n\nType: ${request.type}\nTerm: ${payload['Full Form (English)']}\n\n*Auto-generated by TechMC Glossary*`,
            head: newBranchName,
            base: BASE_BRANCH,
        });

        // 6. Update DB
        await prisma.request.update({
            where: { id: requestId },
            data: { status: 'APPROVED', prUrl: pr.html_url }
        });

        return NextResponse.json({ success: true, prUrl: pr.html_url });
    } catch (error: any) {
        console.error("Admin Action Error:", error);
        return NextResponse.json({ error: error.message || "Failed" }, { status: 500 });
    }
}
